GET http://localhost:3001/blocks

###
POST http://localhost:4000/blocks
Content-Type: application/json

#{
#    "data": "This is the 4123123 block"
#}

###
POST http://localhost:3003/peers
Content-Type: application/json

{
    "peer": "ws://localhost:4000"
}

###
GET http://localhost:3000/me/balance

###
GET http://localhost:3000/transactions